---
title: "Basic Mapping"
author: "Nate Selleck"
date: "10/19/2021"
output: html_document
---
<body style = "background-color:#b1d3aa">

```{r setup, include=FALSE}
pacman::p_load("ggsn","leaflet","mapdata","maptools","rgdal","tidyverse", "readr", "tidyverse", "sf", "leafpop")


```

$~$

<span style="font-size:25px">Static Map - Cheatham Wildlife Management Area</span>


```{r Static Map}

state <- map_data("state")
county <- map_data("county")
cheatham_wma <- data.frame("x" = -87.062749, "y" = 36.190958)

tn <- county %>% 
  filter(region=="tennessee")

cheatco <- county %>% 
  filter(region=="tennessee") %>% 
  filter(subregion=="cheatham")

ggplot() + geom_polygon(data = state, aes(x=long, y = lat, group = group),
                        fill = "white", color="black") + 
           geom_polygon(data = tn, aes(x=long, y = lat, group = group),
                        fill = "tan", color="black") + 
           geom_polygon(data = cheatco, aes(x=long, y = lat, group = group),
                        fill = "green", color="black") + 
           geom_point(data = cheatham_wma, aes(x=x,y=y), color="black") +
  coord_fixed(xlim = c(-91, -81),  ylim = c(34, 37), ratio = 1.2) + 
  xlab("Longitude") + ylab("Latitude") + ggtitle("Cheatham WMA, Cheatham Co., TN")

```

$~$

<span style="font-size:25px">Interactive - Louisiana Waterthrush Behavior at Cheatham</span>

```{r Interactive Map}

lowa_locations <- readOGR("data/lowa.kml")

lowa_locations@data$Description <- c("Male and Female Foraging", "Pair Foraging", "Pair in Tributary", "Countersinging", "Male w/ Unbanded Female", "Countersinging", "Pair Turned Around", "Male Countersinging to Barry B", "Countersinging", "Nesting", "Foraging", "Foraging", "Fecal Sacs", "Foraging", "Singing", "Captured in Net", "Male w/ fledglings", "Countersinging")



leaflet(lowa_locations) %>% 
   addTiles(group = "OSM")%>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB") %>%
  addProviderTiles(providers$Esri.NatGeoWorldMap, group = "NatGeo") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "ESRI") %>%
    setView(lng = -87.062971, lat = 36.187153, zoom = 15) %>%
  addCircleMarkers(popup = lowa_locations@data$Description,
                   label = lowa_locations@data$Name,
                   weight = 2,
                   color = "grey",
                   fillColor = "blue",
                   fillOpacity = 0.7)%>%
  addLayersControl(
    baseGroups = c("ESRI", "OSM", "CartoDB", "NatGeo"),
    options = layersControlOptions(collapsed = FALSE))

```


$~$

<span style="font-size:25px">10 Places in Utah to Visit Before Zion</span>

```{r Test}

utah <- readOGR("data/utah_sites.kml")

utah2 <- data.frame(utah)

pts <- st_as_sf(data.frame(utah),
                coords = c("coords.x1", "coords.x2"), crs = 4326)

img <- c("images/muley.jpg", "images/cave_canyon_tower.jpg", "images/citadel.jpg", "images/calf_creek.jpg", "images/abajo.jpg", "images/castle_valley.jpg", "images/needles.jpg", "images/fruita.jpg", "images/moki_canyon.jpg", "images/natural_bridges.jpg")

pts$img <- img

leaflet() %>%
   addWMSTiles("https://basemap.nationalmap.gov/arcgis/services/USGSTopo/MapServer/WmsServer", layers = "0")%>%
  #addTiles(group = "OSM") %>%
  #addProviderTiles(providers$Esri.NatGeoWorldMap, group = "NatGeo") %>%
 #addProviderTiles(providers$Esri.WorldImagery, group = "ESRI") %>%
  setView(lng = -110.283727, lat = 37.746282, zoom = 8) %>%
  addCircleMarkers(data = pts, 
                   label = utah@data$Name,
                   group = "pts",
                   weight = 1,
                   fillColor = "green",
                   fillOpacity = 0.7)%>%
  addMiniMap(zoomLevelOffset = -4, width = 100, height = 120)%>%
  addPopupImages(pts$img, group = "pts", width = 300)
   #addLayersControl(
    #baseGroups = c("ESRI", "OSM","NatGeo"),
    #options = layersControlOptions(collapsed = FALSE))



```

</body>